/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import static Main.TableCusto.table;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lukas
 */
public class AddCust extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form AddCust
     */
    int index;
    public AddCust() {
        initComponents();
        showCust();
        
    }

    private void showCust(){
        TableCusto data = new TableCusto();
        new TableCusto().execute();
        model = (DefaultTableModel) showCustomers.getModel(); 
        Object rowData[] = new Object[7];
        for (int i = 0; i<TableCusto.table.size(); i++){
            rowData[0] = TableCusto.table.get(i).getid();
            rowData[1] = TableCusto.table.get(i).getname();
            rowData[2] = TableCusto.table.get(i).getnip();
            rowData[3] = TableCusto.table.get(i).getstreet();
            rowData[4] = TableCusto.table.get(i).getpcode();
            rowData[5] = TableCusto.table.get(i).getcity();
            rowData[6] = TableCusto.table.get(i).gettelnum();
            model.addRow(rowData);
        }
        
    }
        public void refreashTable(){
        DefaultTableModel model = (DefaultTableModel) showCustomers.getModel();
        model.setRowCount(0);
        showCust();  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        showCustomers = new javax.swing.JTable();
        addCust = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        editCust = new javax.swing.JButton();
        refreash = new javax.swing.JButton();
        select = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SerwTel Business - Dodawanie klienta");

        showCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID klienta", "Nazwa", "NIP", "Ulica", "Kod pocztowy", "Miasto", "Numer telefonu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showCustomersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(showCustomers);
        if (showCustomers.getColumnModel().getColumnCount() > 0) {
            showCustomers.getColumnModel().getColumn(0).setResizable(false);
            showCustomers.getColumnModel().getColumn(0).setPreferredWidth(5);
            showCustomers.getColumnModel().getColumn(1).setResizable(false);
            showCustomers.getColumnModel().getColumn(2).setResizable(false);
            showCustomers.getColumnModel().getColumn(3).setResizable(false);
            showCustomers.getColumnModel().getColumn(4).setResizable(false);
            showCustomers.getColumnModel().getColumn(5).setResizable(false);
            showCustomers.getColumnModel().getColumn(6).setResizable(false);
        }

        addCust.setText("Dodaj");
        addCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustActionPerformed(evt);
            }
        });

        delete.setText("Usuń");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        editCust.setText("Edytuj");
        editCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustActionPerformed(evt);
            }
        });

        refreash.setText("Odśwież");
        refreash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreashActionPerformed(evt);
            }
        });

        select.setText("Wybierz");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addCust)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editCust)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCust)
                    .addComponent(delete)
                    .addComponent(editCust)
                    .addComponent(refreash)
                    .addComponent(select))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1004, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustActionPerformed
        this.dispose();
        AddUser adduser = new AddUser();
        adduser.setVisible(true);
    }//GEN-LAST:event_addCustActionPerformed

    private void refreashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreashActionPerformed
        refreashTable();
            // TODO add your handling code here:
    }//GEN-LAST:event_refreashActionPerformed

    private void showCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showCustomersMouseClicked
        index = showCustomers.getSelectedRow();

    }//GEN-LAST:event_showCustomersMouseClicked

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        String id = TableCusto.table.get(index).getid();
        AddOrder addorder = new AddOrder();
        addorder.id_cus.setText(id);
        this.dispose();
        addorder.setVisible(true);
    }//GEN-LAST:event_selectActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        AddQuery updat = new AddQuery();
        AddQuery.query = "DELETE FROM CUSTOMERS WHERE ID="+String.valueOf(TableCusto.table.get(this.index).getid());
        new AddQuery().execute();
        refreashTable();
    }//GEN-LAST:event_deleteActionPerformed

    private void editCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustActionPerformed
    
    }//GEN-LAST:event_editCustActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCust().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCust;
    private javax.swing.JButton delete;
    private javax.swing.JButton editCust;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreash;
    private javax.swing.JButton select;
    public javax.swing.JTable showCustomers;
    // End of variables declaration//GEN-END:variables
}
